site_name: Spaju Learning
repo_url: https://github.com/TheNameXDD/Spaju-learning
edit_uri: edit/main/docs/

theme:
  name: material
  language: ru
  custom_dir: theme

plugins:
  - search:
      lang:
        - ru
        - en

  - git-committers:
      repository: TheNameXDD/Spaju-learning
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]

nav:
    - На главную: https://spaju.engineering/learning/
    - Внести вклад: editing/
    
    - Робототехника:
          - ABB робототехника:
                - Про ABB роботов:
                - Про RobotStudio:
