site_name: Spaju Learning
repo_url: https://github.com/TheNameXDD/Spaju-learning
edit_uri: edit/main/docs/

theme:
  name: material
  language: ru
  custom_dir: theme

plugins:
  - search:
      lang:
        - ru
        - en

  - git-committers:
      repository: TheNameXDD/Spaju-learning
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]

nav:
  - На главную: https://spaju.engineering/learning/
  - Внести вклад: editing/index.md
  - Робототехника:
    - О роботах:
      - Что такое робот?: robotics/what-is-robot/index.md
      - Промышленные роботы: robotics/what-is-robot/industrial-robots/index.md
      - Типы роботов: robotics/robots-types/index.md
    - ABB робототехника:
      - Про ABB роботов: robotics/abb/about/index.md
      - RobotStudio: robotics/abb/robotstudio/index.md
